name: mindshed_app
description: "MindShed"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  crypto: ^3.0.2
  cupertino_icons: ^1.0.8
  audioplayers: ^6.3.0
  intl: ^0.20.2
  shared_preferences: ^2.5.2
  tflite_flutter: ^0.11.0
  json_annotation: ^4.9.0  
  flutter_secure_storage: ^8.1.0
  flutter_local_notifications: 15.1.1
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/1024.jpg"
  adaptive_icon_foreground: "assets/images/logo-2.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/decision_model.tflite
    - assets/decision_labels.json
    - assets/ai.tflite
    - assets/wellness_grader.tflite   
    - assets/wellness_meta.json      
    - assets/images/pet.jpg
    - assets/images/logo.png
    - assets/ambient/lr.mp3
    - assets/ambient/hr.mp3
    - assets/ambient/c.mp3
    - assets/ambient/w.mp3
    - assets/ambient/o.mp3

  fonts:
    - family: HappyMonkey
      fonts:
        - asset: assets/fonts/HappyMonkey-Regular.ttf